### ISSUE TITLE
Layer re-ordering crashes the app

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#100]
From Alana and @saralizj.

Seems like any re-ordering of the layers makes the app crash.

I couldn't reproduce the bug, but I was using @jameljoseph  latest code. I'll check with release 1.1, which is the version they are working on.

**Comment by jameljoseph** [comment]
I will try this but the last time i reordered the layers it didnt crash

**Comment by ghuotvez** [comment]
> I will try this but the last time i reordered the layers it didnt crash

Yeah same for me. Maybe we need to try with a sqlite added in there from another project. I'll check later too. Thanks Jamel!

**Comment by jameljoseph** [comment]
I tried it on both tablets and I could not replicate the crash

**Comment by ghuotvez** [comment]
> I tried it on both tablets and I could not replicate the crash

Alright thanks for the try!

**Comment by ghuotvez** [comment]
I've uninstall the app on my laptop, installed v1.1 from github, started from scratch and wasn't able to reproduce the problem. With either 2 tpks or with 2pks and 1 sqlite coming from another GSC Field App project.

I'm waiting for more details from Alana. Maybe it was only on the tablets with some precise windows build.

**Comment by ghuotvez** [comment]
> It’s happening on the tablet. 
> We are using W10 Pro version -21H1
> It’s not a big deal, and one of the students said that if you load the layers, then save then close the app, and reopen, you can then reorder the layers without crashing the app.
> I haven’t tried this though.
>

**Comment by ghuotvez** [comment]
I was able to get a testing on a tablet with 21H1 and still couldn't reproduce the problem. I had 3 tpks in there. I'm wondering if its related to memory usage. Could it be that moving around large tpks makes the app freeze a little a then Windows crashes it?

**Comment by ghuotvez** [comment]
@saralizj I was able to get some errors on screen with a tablet here. There was some pink/red error box telling us about something being null. I have a manual fix for that, but it's quite technical.

- Navigate to where the app is installed which is C:\Users\xxxx\AppData\Local\Packages\GSCFieldApp_npcr2acgj3y9m\LocalState (note that GSCFieldApp_npcr2acgj.... might be spelled different on the table, but will still start with GSCFieldAPP)
- In this localstate folder, you should see sub folders with numbers, they correspond to each field note books in the app. Navigate to the proper one. In there you should see the database, tpks and an extra file.
- Open this extra file named mapPageLayer.json, this is where the layers configuration is stored (ordering, hidden/visible, opacity). In there at the far end you might find some null references, that you'll need to erase. It could be tricky since the json opened in a note pad will appear on 1 line. Opened in a proper editor, it could appear like so.

```
[
  {
    "LayerName": "Canada_Default_10.tpk",
    "LayerSettings": {
      "LayerOpacity": 100,
      "LayerVisibility": true,
      "LayerOrder": 0
    }
  },
  {
    "LayerName": "TPK_Testing_16.tpk",
    "LayerSettings": {
      "LayerOpacity": 100,
      "LayerVisibility": true,
      "LayerOrder": 0
    }
  }
]
```

The null references can easily be found by looking at LayerName, which will be set to null instead of the actual file name. Removing all that's inside the curly braces before layer name should work it out.

If not, deleting the whole file and adding back all tpks might also do the trick.

**Comment by ghuotvez** [comment]
@jameljoseph  I guess an easy fix would be to code a method that cleans this file of null rather then crashing the whole thing.

**Comment by jameljoseph** [comment]
ok gab I will check it out.  I took a few days off since my mother came to visit but im working today and tomorrow.  Then I am off for most of next week

**Comment by ghuotvez** [comment]
The thing is, I already added code in there to prevent this from happening: https://github.com/NRCan/GSC-Field-Application/blob/a12f3d0e0c73421819377f4cd9c12770ff5d8eca/GSCFieldApp/ViewModels/MapPageViewModel.cs#L2048 

But I also found, that when trying to read the file, the code will deserialize directly to a MapLayerSetting object with double, int and bool variable types. If any entries is null, this deserialization process will fail for sure.

**Comment by ghuotvez** [comment]
Fixed it and also on any save, if anything is null, it'll be cleaned out too.
