### ISSUE TITLE
structure form wont save new structure value when changed

### ISSUE THREAD

**Issue by jameljoseph** [NRCan/GSC-Field-Application#101]
Create a structure record, then once you go back and change the structure type and save, the new value was not saved.

**Comment by jameljoseph** [comment]
fixed

**Comment by ghuotvez** [comment]
oh nice you were able to get it to work? how did you manage?

**Comment by jameljoseph** [comment]
It seems to work yes.  I found the right spot for the focus and used FocusState.programmatic and it now works.  I will upload it for you when I fix one more thing in the mineral form

**Comment by ghuotvez** [comment]
Awesome thanks!
