### ISSUE TITLE
Uniformisation des champs "idname"

### ISSUE THREAD

**Issue by AnnickMorin** [NRCan/GSC-Field-Application#105]
Allo!
Suite à notre discussion de ce matin
voici une proposition d'uniformisation pour les champs "idname" (Du côté de la FODR se sera fait aussi)

- [x] f_structure.strucname devient f_structure.strucidname
- [x] f_location.locationname devient f_location.locationidname
- [x] f_earth_material.earthmatname devient f_earth_material.earthmatidname
- [x] f_station.stationname devient f_station.stationidname
- [x] f_sample.samplename devient f_sample.sampleidname
- [x] f_document.documentname devient documentidname
- [x] f_environment.environname devient environidname

Pour les tables F_MINERALIZATION_ALTERATION, F_MINERAL, F_FOSSIL, F_PALEO_FLOW et F_SOILPRO  tout était tiguidou :)

**Comment by ghuotvez** [comment]
Well I wasn't able to reproduce this...might have been a bad internet connection on my laptop. I'll close for now. I don't think it's related to the new code.
