### ISSUE TITLE
Dip value for the structure table does not show up in the window on the main page 

### ISSUE THREAD

**Issue by jameljoseph** [NRCan/GSC-Field-Application#107]
When you create a new structure, enter an azimuth and dip, and save the record, you see the azimuth value but not the dip value for each structure on the main page.  For example, if you create a structure and the values are 123 for the azimuth and 45 for the dip, the main page shows "123 /  ".

When I run the code in visual studio, I get a stoppage where a number cannot be converted form one file type to another.  This is not a critical error that stops the program, so you hit continue and the rest of the code still runs so maybe they are related??

**Comment by jameljoseph** [comment]
The data types for azimuth and dip are the same so no issues with data conversions with the error I got

**Comment by jameljoseph** [comment]
fixed, needs to be tested by gab to make sure it works

**Comment by ghuotvez** [comment]
@jameljoseph I'll test that out for sure, but I can't find the code.

**Comment by ghuotvez** [comment]
All seems fine about the dip, good job. I'm still wondering why it wouldn't even be able to parse an int from a string.

**Comment by jameljoseph** [comment]
No clue.  I tried all the options and it would crash the application.
