### ISSUE TITLE
Annoying top bar

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#111]
We can't see any of the icons names in map page top bar menu. 

![image](https://user-images.githubusercontent.com/19910413/137787679-cadfe63b-6346-4a18-a822-8576a3722841.png)

**Comment by jameljoseph** [comment]
So I fixed toolbars for 3 pages (settings, field book, and map page) as well as added a bottom toolbar to the field book page and moved 3 buttons to that bottom toolbar.

**Comment by jameljoseph** [comment]
Only 1 issue and that is with disappearing text for icons where the text is below.  If we move the the text to the side then the issue goes away, but it will require more of the toolbar and for smaller screens, it might get truncated.

**Comment by ghuotvez** [comment]
I really like the latest inputs. Good job.

I found a little glitch on map page with the GPS icon, I used to have the location icon, 

We can see an example in my window bar, but in the app it's just a little dot. I've checked the commit but I can't find why it would suddenly have changed.
![image](https://user-images.githubusercontent.com/19910413/144312370-9fd92080-57ae-4b4c-af7f-c177e91f4b65.png)

**Comment by jameljoseph** [comment]
Fixed!!

**Comment by jameljoseph** [comment]
I just noticed another icon is smaller now so I am fixing it now.

**Comment by jameljoseph** [comment]
It looks good to go now so we can test on tablets and if it works we can close this bug

**Comment by ghuotvez** [comment]
Awesome thanks!

**Comment by jameljoseph** [comment]
I have been finally able to put the app on one of the tablets without it crashing and the buttons look great and work so I will close this.

**Comment by ghuotvez** [comment]
Alright! Thanks! 😄
