### ISSUE TITLE
Location - edit fails on saving

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#119]
For testing purposes I took some stations with a really bad location, actually pretty much nothing.

Then I went into the location form to edit it and clicked saved without modifying anything.  Now I can't get out of the location form or even edit it to fix the problem. There is a warning message that pops on screen and prevents user from closing it or going elsewhere.

![image](https://user-images.githubusercontent.com/19910413/148241432-1e02d944-d8f5-4054-93e6-c4fbae6ae3c9.png)

**Comment by jameljoseph** [comment]
i will try it out today gab and see what i get

**Comment by jameljoseph** [comment]
I couldnt replicate this.  When you say bad location.  You mean bad accuracy correct?

**Comment by ghuotvez** [comment]
I meant worst accuracy possible and I was still getting a 0,0 location because I had problems with the wifi. This is unlikely to happen to anyone. Not a priority bug.

**Comment by ghuotvez** [comment]
Can't reproduce it myself even after disconnecting Wi-Fi on laptop. Will close.

**Comment by ghuotvez** [comment]
I finally was able to reproduce this, the location didn't take off and I took a station which had 0,0 as location. Opened location form and couldn't get out of it.

**Comment by ghuotvez** [comment]
The warning was shown when a location 0,0 was found when saving, I added a condition that this must be shown only if within a manual entry location not a GPS one, since those fields are disable for modifications.
