### ISSUE TITLE
Map info disapears after adding a layer

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#124]
When creating a new field book, then adding a layer, I'm missing the top left information about coordinates and projection.

**Comment by ghuotvez** [comment]
This problem has been there for quite a long time it seems. 

This commit and the one after have a broken map info graphic:
https://github.com/NRCan/GSC-Field-Application/commit/88891c8954958d2e53d9f6e6e225a5f5065ef257

The previous one (mine), has a functional one: 
https://github.com/NRCan/GSC-Field-Application/commit/1fda1d60385e4b4db33a1f9f524f07e01746770a
Same for the previous one (Jamel), it works fine:
https://github.com/NRCan/GSC-Field-Application/commit/6fd736e401dc81cb45e6081e9ff5c7df5e7d1f87

**Comment by ghuotvez** [comment]
So, basically, below line of code (regarding the mapview itself) was taken from line 125 and pushed to 153, reverting this little change fixed the bug...

https://github.com/NRCan/GSC-Field-Application/commit/88891c8954958d2e53d9f6e6e225a5f5065ef257#diff-ffae5b36053509b7833078c782ecbe4ebc7b62cb25e1a91e3ea368211f706a28R153 

I also have added a RaisePropertyChange for _currentProjection so the new projection actually gets shown on the map page.

**Comment by jameljoseph** [comment]
Ok.  Well I was able to see the coordinates and projection now when I load a layer.

**Comment by jameljoseph** [comment]
Now we know how to fix this, with code and in designer view!!

**Comment by jameljoseph** [comment]
I tested both mine and your fixes on the computer and tablet and both work so we can close this one Gab.
