### ISSUE TITLE
Loading layers - missing waiting cursor

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#125]
When loading any new layers, the waiting cursor seems to disapear.

**Comment by jameljoseph** [comment]
So is the waiting cursor the circle that seems to run clockwise?  IF so When I loaded the layers, I got that showing briefly before the layers were shown

**Comment by ghuotvez** [comment]
Yes, exactly. It used to be displayed until everything was loaded and rendered on screen. Maybe it's my laptop who's lagging a bit? Does it work well on the tablets too? In that case it's really just my laptop haha.

**Comment by ghuotvez** [comment]
There was an extra call to the waiting cursor that was probably breaking the whole thing since it was called multiple times on top of each other. Removed the one from the view.cs and it works.
