### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#129]
Update the readme file of the project so tihe .io url (https://nrcan.github.io/GSC-Field-Application/) presents the latest we have.

- Add download link of the latest package (V1.2)
- Visual studio 2019-2022 is being used now
- Add link to top ten feature youtube video.
- Add link to wiki page for more info (I think most people doesn't know it exists)

**Comment by rcocking** [comment]
Hi Gabriel,

I have finally gotten to doing some of the things you asked. 😊


  1.  On the main page (readme.md) I have added a link to the version 1.2 download page in English and my version of French (thanks to DeepL). Please check my translation. 😊
  2.  Updated that we are using Visual studio 2019-2022
  3.  Added a readme.md link to the wiki Again, please check the French version.
  4.  Added a readme.md link to the Top 10 video

There is a certain amount of English in the French section. I added a DeepL translation under Format de Donnee. Have review and see if it is good, then please delete the English.

Thanks!
Rob

From: Gabriel Huot-Vézina ***@***.***>
Sent: Thursday, February 24, 2022 5:36 AM
To: NRCan/GSC-Field-Application ***@***.***>
Cc: Robert Cocking ***@***.***>; Assign ***@***.***>
Subject: [NRCan/GSC-Field-Application] Update readme (Issue #129)


Update the readme file of the project so tihe .io url (https://nrcan.github.io/GSC-Field-Application/<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnrcan.github.io%2FGSC-Field-Application%2F&data=04%7C01%7Crobert.cocking%40NRCan-RNCan.gc.ca%7C14b5896dcd864a2027d808d9f79a9956%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637813066756108505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wLPSF4dZbhqNIjZl4OgJ%2Fn1RtDj3b2viraSiSc967ps%3D&reserved=0>) presents the latest we have.

  *   Add download link of the latest package (V1.2)
  *   Visual studio 2019-2022 is being used now
  *   Add link to top ten feature youtube video.
  *   Add link to wiki page for more info (I think most people doesn't know it exists)

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNRCan%2FGSC-Field-Application%2Fissues%2F129&data=04%7C01%7Crobert.cocking%40NRCan-RNCan.gc.ca%7C14b5896dcd864a2027d808d9f79a9956%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637813066756108505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9ixZ8jhYo0YSkuFvocwO5GwSKvulHcC1c6f0dsZX4pQ%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMNDI2LWNKBUM4JB4TBMUZ3U4YX4BANCNFSM5PHM36OA&data=04%7C01%7Crobert.cocking%40NRCan-RNCan.gc.ca%7C14b5896dcd864a2027d808d9f79a9956%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637813066756108505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=md0wbuwLmTHxp%2FrUMLav%2BT0DKT3N1RxzJM2hn4%2FPF0I%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crobert.cocking%40NRCan-RNCan.gc.ca%7C14b5896dcd864a2027d808d9f79a9956%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637813066756108505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FRjcBJqTf8VBXPp00Nrx6QAqOtbkMpCkTx7IJZOzios%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crobert.cocking%40NRCan-RNCan.gc.ca%7C14b5896dcd864a2027d808d9f79a9956%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637813066756108505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Zk6zx7dtyrLnu29Y7Vl%2BdhoI%2Bp7PIsaXYsZjrnE8SQc%3D&reserved=0>.

**Comment by ghuotvez** [comment]
Alright thanks a lot Robert! I've corrected the extra english part in the french one. The deepl translation was good, that's a neat trick you used.
