### ISSUE TITLE
Dip - no measure

### ISSUE THREAD

**Issue by eygirard** [NRCan/GSC-Field-Application#133]
When the dip measure is unknow it's probably a pertinent way to indicate it in Attitude field with the word "TREND" and no data in attitude.

**Comment by ghuotvez** [comment]
> Le questionnement d’Étienne concerne uniquement les données planaires.
> C’est le cas ou le géologue est capable de prendre une valeur d’azimuth mais ne peut pas voir ou même estimer le pendage (i.e. le dip). On s’est souvent poser la question à savoir quoi faire dans ces cas. Dans FieldLog, à l’époque, on mettait la valeur de 99 dans DIP. Mais cette solution de tient pas la route et je crois que c’est Étienne qui proposait mettre la valeur DIP = Null et mettre la valeur TREND dans le champ ATTITUDE (au lien de inclined, vertical ou horizontal).
> Personnellement, je trouve l’idée parfaite. Tu pourras confirmer avec Étienne.
>

**Comment by ghuotvez** [comment]
- Add "Trend" within attitude planar picklist.
- Add possibility to enter null values in dip. Having null would then auto-select Trend in Attitude.

**Comment by ghuotvez** [comment]
I reoponed the issue since saving a structure records without any dip value forces 0 to be saved.
