### ISSUE TITLE
x64 bit only? Really?

### ISSUE THREAD

**Issue by 29Sheriff** [NRCan/GSC-Field-Application#151]
I wonder why you will make an app like this and then decide to make it only compatible with x64 bit platforms. Many field data collectors come with x86 bit platforms. You should consider making a 32 bit compatible version. I can't see why you would make it 64 bit only platform. Tried. But can't

**Comment by ghuotvez** [comment]
I'll pack a new 32 bits version, it wasn't intentional.

**Comment by ghuotvez** [comment]
New packages available: https://github.com/NRCan/GSC-Field-Application/releases/tag/2.1.0
