### ISSUE TITLE
Location accuracy issue and constantly trying to find location

### ISSUE THREAD

**Issue by jameljoseph** [NRCan/GSC-Field-Application#168]
So when I visited Melanie on site, she told me that in many cases, when you are in mapview, either your location is found right away with 1 or 2 m accuracy, or the app cannot find your location and it searches forever, making it unreliable to make a station with coordinates you are confident with unless you know exactly where you are and you either tap your location in or write in the coordinates using an external gps.

**Comment by ghuotvez** [comment]
This might be tied to the satellite, it depends on what latitude they are. Or this could also be a problem with either #138 or #139. Current dev branch might fix this issue.

**Comment by jameljoseph** [comment]
I found that if I go from dataview to mapview, the users location cannot be found almost all the time

**Comment by ghuotvez** [comment]
Oh! That targets the search for a fix thanks. There might be a refresh problem going on there.

**Comment by ghuotvez** [comment]
Did not occur since latest dev.
