### ISSUE TITLE
Save/Close icons - make them bigger

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#169]
For some reasons it seems harder to click on those lately. Also, we had some comments from peope on field strugling to click on those with dirty hands and trying to do something quick.

**Comment by ghuotvez** [comment]
@jameljoseph

**Comment by jameljoseph** [comment]
Hey Gab, so I can make the buttons wider, but the length is an issue.  The header only seems to grow after I get to 100 pixels or bigger.  I want it around 80 but it just defaults back to original size which is a pain.

**Comment by jameljoseph** [comment]
Talking with Kaz on this, do you recommend us going into the OS settings and making the app bigger if users come across this issue?

**Comment by ghuotvez** [comment]
Not necessarily, I think what you did is good enough. There is already more grip to it.
