### ISSUE TITLE
Disapearing layers in menu

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#176]
For some reasons, we have a geologist who at some point on the field, started having trouble with layers. They would disapear from the menu but still be visible on the map. Then clicking on the layers menu would pop an error message about null values.

When this started on a given field notebook, he created a new one and it started happening again later one, 11 stations in.

**Comment by ghuotvez** [comment]
Might be related to #174.

**Comment by ghuotvez** [comment]
I was able to reproduce this problem, it's quite annoying.

**Comment by ghuotvez** [comment]
On the tablets also it can cause the app to crash, it seems like a memory related problem.

**Comment by ghuotvez** [comment]
Pierre was able to reproduce this while overseas.

**Comment by jameljoseph** [comment]
I cannot reproduce this either gab!!

**Comment by ghuotvez** [comment]
> I cannot reproduce this either gab!!

Yeah that's a tough one that seems to pop only when user is the farthest away possible from any human being ... I tried reproducing the same "manipulation" that would occurs in a field camp, but nothing changes...

**Comment by ghuotvez** [comment]
This issue did not occurred in the field 2023 season. Will close.
