### ISSUE TITLE
New obs type in station form

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#179]
Add a new observation type field in station for surficial theme.  Here's the difference between station type and obs type:

•	Obs_type:  ground or remote
•	Station type:  dughole, ice flow indicator, section, borehole, auger hole,  natural exposure, photograph, observation, etc. 

Asked by 2 scientists to get a clear difference between their station types and how they were seen or collected.

**Comment by ghuotvez** [comment]
New text field OBSSOURCE created, and it'll contain the the picklist values of ground and remote. We'll keep current OBSTYPE field with the long list of values (dughole, ice flow indicator, section, borehole, auger hole, natural exposure, photograph, observation, etc.). 

@fletour

**Comment by fletour** [comment]
@ghuotvez don't forget to add explicit name of the table

**Comment by ghuotvez** [comment]
@fletour Sure, here's the full name F_STATION.OBSSOURCE. As for the type, there is only text in sqlite, but there is only two possible values in there. 50chr would be more then enough.
