### ISSUE TITLE
Add a new term in the picklist of the f_structure.attitude field "trend only"

### ISSUE THREAD

**Issue by AnnickMorin** [NRCan/GSC-Field-Application#182]
When you see a trend on the outcrop but it is not possible to take a dip measurement. 
The field Dip/Plunge stay empty.
The term that should be added is "trend only" (for planar measurement only) With this term there is no confusion if the user forgot to write the measurement. This term should replace "undefined"

This suggestion is from the FODR team.

**Comment by ghuotvez** [comment]
@AnnickMorin is the same as this one? #133

**Comment by ghuotvez** [comment]
Trend only now replaces Trend from #133.

**Comment by ghuotvez** [comment]
@fletour

**Comment by ghuotvez** [comment]
## Correction

Value "Trend only" isn't found in the database, still showing "trend".

## Replace

Replace value "undefined" by "trend only".
