### ISSUE TITLE
Move the Report_link field from F_STATION to F_LOCATION ?

### ISSUE THREAD

**Issue by AnnickMorin** [NRCan/GSC-Field-Application#188]
Dans le projet de Hopedale labrador de ALana Hinchey, elle n'est pas à l'aise avec une sqllite. Je lui fourni une gdb dans le même schéma que la GSC field app. Gabriel m'a fourni un xml "GSCFieldApp_sqllite_in_gdb_Version1_5.xml" pour faciliter la conversion.
Dans ce schéma, on retrouve un feature FS_LOCATION. Dans ce feature, on ne retrouve pas le champ Report_link.

![image](https://user-images.githubusercontent.com/49729155/212402934-dfb1d85b-b4d1-4740-b39c-842f68fad099.png)

Cependant, dans la bd sqlite, on retrouve FS_STATION qui est une "table" geospatiale. À l'intérieur on retrouve un mixte des champs de F_STATION et F_LOCATION. À l'intérieur on retrouve le champ report_link. 
![image](https://user-images.githubusercontent.com/49729155/212404485-395ebb4d-8a77-4861-ae2d-4b1efa634f89.png)

Lorsqu'on s'est parlé cette semaine tu voulais peut-être enlever tous les FS dans la sqlite. 

Est-ce qu'il serait une bonne option de déplacer le champ report link de la f_station vers la F_location?  Dans le futur je vais sûrement, transformer encore d'autres données en format sqlite en gdb. Le champ Report_link est primordial.

**Comment by ghuotvez** [comment]
Donc, l'idée est d'avoir accès au champs "REPORT_LINK" à même une entité spatiale afin qu'un "get feature info" puisse retourner l'URL et laisser l'usager naviguer vers le rapport HTML si il y en a un.

**Comment by ghuotvez** [comment]
@fletour PTI.
