### ISSUE TITLE
Field book - Restore - Field notes are empty

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#196]
When restoring a field book, for some reasons all forms are hidden in field notes, except station and location. When checking in the settings, all toggles are turned on. Manually toggling them off then on again will force the field note page to show them back.

**Comment by jameljoseph** [comment]
Hey Gab, so when I try to create a new station now, I get this error:


▶ | $exception | {"table F_LOCATION has no column named NTS"} | SQLite.SQLiteException

**Comment by ghuotvez** [comment]
Can't reproduce on desktop, but still happening on tablet after last dev package.
