### ISSUE TITLE
Database format Spatialite vs Geopackage

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#215]
### Discussed in https://github.com/NRCan/GSC-Field-Application/discussions/142

<div type='discussions-op-text'>

<sup>Originally posted by **ghuotvez** July  8, 2022</sup>
Currently, we're using an SQLite database. We do have some python script that enables SpatiaLite extension to work, we can then use some point features for location and some more neat process. But then, although SpatiaLite is native to QGIS, the current format isn't editable within ArcGIS Pro in it's current form because the tables/features are missing an ESRI OID field.

We know that Geopackages and SpatiaLite databases are editable within Arc Pro 2.9 if created from within the software. It adds the much needed OID field.

Use of SQLite was found to be more light and faster for our usage on site as opposed to a Spatialite who comes blank with around 6-7 Mb compared to a couple of Ko for sqlite. That was, 5 years ago.

On another side latest format of geopackage (1.3) weights less then 200Ko compared to a blank spatialite database.

More testing is needed.</div>

**Comment by ghuotvez** [comment]
Well...change of planned. I didn't read the fine prints and lite licence for ESRI sdk can't open geopackages...
https://developers.arcgis.com/net/license-and-deployment/license/#license-string

Will drop this feature then.

**Comment by ghuotvez** [comment]
# Planned schema changes to make it work
Some slight changes are needed in the schema to make it work in QGIS and ArcGIS Pro by default.

## Features

- Convert F_LOCATION to a Point feature
- Convert FS_TRAVERSE_POINT to a Point feature
- Convert FS_TRAVERSE_LINE to a line feature
- Delete FS_Fieldcamp since it's already available within F_STATION as a station type.
- Use ArcGIS geometry field naming, so it works in both gis software.

## Prime keys
As specified in the geopackage definition, all tables/features needs an integer prime key field. 

- Add a prime key field in all tables/ features

**Comment by ghuotvez** [comment]
# Problems 

1. Creating a new point feature with MakePoint() spatialite query does not show the point within ArcGIS.
2. Creating a new geopackage and copying the tables from a sqlite to a geopackage in Arc introduces new field types like MEDIUMINT or TINYINT, which are not SQLite valid field types. This crashes the the net-pcl sqlite library when integers are empty. Crashes on constraint. 

# Solved
1. -
2. Recreated the tables with sqlite field formats instead of the ones introduced by Arc. See https://www.geopackage.org/spec131/index.html#gpb_spec section 1.1.1.1.3 for more information on those new field types.

**Comment by jameljoseph** [comment]
I will test this out now Gab

**Comment by ghuotvez** [comment]
# Upgrade option
The option will need heavy edits on the database side in order to convert all prime and foreign keys to integer. I suggest adding temporary fields in the copied sqlite database in which an update will occurs and try to come up with an integer based on the GUID. Method that should be able to recreate the same int when it comes the time to update the foreign keys.

**Comment by ghuotvez** [comment]
### Delete
Make sure the delete method takes a proper int now

### Parent IDs
Fieldnote class needs to get an int as parent ids

**Comment by jameljoseph** [comment]
I added some code that would help convert splite to geopackage for old sqlite databases but it is not quite working
