### ISSUE TITLE
Add new Photo, the category is already loaded

### ISSUE THREAD

**Issue by jameljoseph** [NRCan/GSC-Field-Application#216]
So when I make a new photo record, save it, and then click on new photo record, i noticed the category is already filled in.  

Should we remove the category?

**Comment by ghuotvez** [comment]
Yeah it was designed like so. Had a request to get an outcrop category selected automatically. I think from the bedrock team. Else if someone wants to change it, user can edit the picklist for photos and uncheck default value option for category field.

**Comment by jameljoseph** [comment]
sounds good!
