### ISSUE TITLE
convert sqlite to geopackage

### ISSUE THREAD

**Issue by jameljoseph** [NRCan/GSC-Field-Application#221]
If users want to add old field books to the app, we need to convert eh underlying db from sqlite to geopackage

**Comment by ghuotvez** [comment]
Yes, I was working on that before leaving for march break. I was able to create a new geopackage and was about to try and mitigate the data from older database into the new one. We need to find a way of converting the IDs to some int on the fly when loading.

**Comment by ghuotvez** [comment]
I can keep on working on that portion if you want to concentrate on other things.

**Comment by ghuotvez** [comment]
See #215
