### ISSUE TITLE
working on db in qgis

### ISSUE THREAD

**Issue by jameljoseph** [NRCan/GSC-Field-Application#223]
I am testing whether we can actually load the geopackage in qgis and make forms that would allow users to add or edit records to their db in qgis

**Comment by jameljoseph** [comment]
Qfield doesnt seem to allow a user to access child forms when making a station, even though the relationships are created and when you make a station in QGIS, you can access the child forms when you create a new station.

**Comment by ghuotvez** [comment]
I'll close since we can't move on with QField based on this. Thanks Jamel!

**Comment by jameljoseph** [comment]
sure thing!!
