### ISSUE TITLE
Link to github in about page

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#229]
Add some links in the about page that refers our project page on github and one for the issue board.

- https://nrcan.github.io/GSC-Field-Application/
- https://github.com/NRCan/GSC-Field-Application/issues
- https://github.com/NRCan/GSC-Field-Application/wiki

Add a section between contact and team

Update my email to the new nrcan one.

**Comment by ghuotvez** [comment]
@rcocking I've reworked a bit the about page, here's a look. If you have any comments I'll take them.

![image](https://user-images.githubusercontent.com/19910413/228885076-7d0b21da-7ff2-466c-8cce-389630d0fc29.png)

**Comment by rcocking** [comment]
Looks great to me!
