### ISSUE TITLE
App se ferme en ajoutant une station à l'aide d'un tap. 

### ISSUE THREAD

**Issue by eygirard** [NRCan/GSC-Field-Application#233]
Sur mon ordinateur (windows français) créer un nouveau projet surficial. Ajouter une station manuellement. / sauvegarde. Le logiciel ferme.

Facile de reproduire le problème

**Comment by ghuotvez** [comment]
Ça semble bien fonctionner en anglais, je vais aller voir en français.

**Comment by jameljoseph** [comment]
Had to translate this but yes works well in english.  I dont have french windows so I cant help much with this one

**Comment by ghuotvez** [comment]
Will close, this did not happened during field season and on later versions.
