### ISSUE TITLE
Surficial - photo crash

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#237]
Nouvelle photo ferme l'application en mode photo extended plutôt que photo normale.

**Comment by jameljoseph** [comment]
So I converted what you said to english.  I made a surficial field book and took a picture both from making a station first and also from making a photo station.  The pictures I took I used all the HDR settings I saw on teh left of the image and none of them crashed my app.  How do you get to extended mode?

**Comment by ghuotvez** [comment]
Go in the setting page, then other tab, then there is a slide toggle under field photos.

**Comment by ghuotvez** [comment]
I was able to fix this, but this arise another problem regarding the exposed relationship between table with the new geopackage format. Since the document/photo table could be linked to other tables, like sample, it fails here because of the new format. By having all different foreign keys in one field, the code fails if something other then station is selected since document-station is the only exposed link. Whenever document table has more foreign key fields and more links this will be possible again. For now I'll hide for good those two combo boxes that are causing problems.
