### ISSUE TITLE
Mineral - Mode

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#246]
Shown mode in percentage always omits the first recorded minerals.

**Comment by jameljoseph** [comment]
Hey Gab,  So When I go into the mineral form and select a mineral name, then select a mode and save, it saves the mineral name

**Comment by ghuotvez** [comment]
> Hey Gab, So When I go into the mineral form and select a mineral name, then select a mode and save, it saves the mineral name

But does it also save the mode? Then after it when you create a second one does it take into account the number put in mode field from the first record?

**Comment by jameljoseph** [comment]
Hey Gab, so it shows the mode as well.  It does not take into account the value so I am not sure if we can put code in to check and make sure the values are not over 100% if there are multiple minerals

**Comment by ghuotvez** [comment]
> Hey Gab, so it shows the mode as well. It does not take into account the value so I am not sure if we can put code in to check and make sure the values are not over 100% if there are multiple minerals

Hum, alright. That's one weird behavior. I'll tackle it today and check.

**Comment by ghuotvez** [comment]
> Hey Gab, so it shows the mode as well. It does not take into account the value so I am not sure if we can put code in to check and make sure the values are not over 100% if there are multiple minerals

I've taken your idea Jamel and made the text go red when going over 100%. I've also fixed the weird behavior since I was able to finally reproduce it.
