### ISSUE TITLE
Dictionnary update

### ISSUE THREAD

**Issue by annmorin** [NRCan/GSC-Field-Application#255]
Yo!
Dans le champ TEXTSRUC pour la table F_EARTH_MATERIAL et F_MINERALIZATION_ALTERATION, il y a une petite faute pour le mot "cummulate" devrait être cumulate.
![image](https://github.com/NRCan/GSC-Field-Application/assets/133264523/ea09f03e-ba61-44f8-9d9f-db7626d7f157)

**Comment by AnnickMorin** [comment]
Hello :)
il y a des doublons dans  le champ TEXTSTRUC:
-equigranular
-fibrous
-glomeroporphyric
-spotted

Aussi effacer le terme "TYPE"

il y a un doublon dans le champ lithqualifier

calc-alkaline

**Comment by ghuotvez** [comment]
For some reasons I've found yet again those duplicate values in the datbase.

**Comment by ghuotvez** [comment]
List of lith group with duplicates that will need some clean-up

- metaplutonic
- metasedimentary
- plutonic
- sedimentary

I'vec check other problems like TYPE and lith qualifier duplicate and they were actually fixed. Seems like the above were mishaps.
