### ISSUE TITLE
Mineral controls aren't emptying after selection 

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#261]
After selecting a mineral, the box should empty itself so user doesn't have to erase it before entering something else.

**Comment by jameljoseph** [comment]
So I tried using The suggestionChosen event and also putting code in the QuerySubmitted event to empty the autosuggestbox and it always rechoses the autosuggestbox and doesnt save what I chosen.

**Comment by ghuotvez** [comment]
> So I tried using The suggestionChosen event and also putting code in the QuerySubmitted event to empty the autosuggestbox and it always rechoses the autosuggestbox and doesnt save what I chosen.

QuerySubmitted should have done the trick. What are you using to empty the box?

**Comment by jameljoseph** [comment]
MineralAutoSuggest.Text = string.Empty;

**Comment by jameljoseph** [comment]
fixed and committed to dev-app for review
