### ISSUE TITLE
Update dictionnary Lithdetail metamorphic

### ISSUE THREAD

**Issue by AnnickMorin** [NRCan/GSC-Field-Application#264]
hello 
il faudrait vérifier  les metamorphic status "edited" dans le fichier à Pierre.
Il n'aurait pas été mis à jour

**Comment by ghuotvez** [comment]
|OBJECTID|TERMID|CODETHEME|RELATEDTO|CODE|DESCRIPTIONEN|DESCRIPTIONFR|ITEMORDER|DEFAULTVALUE|CREATOR|CREATEDATE|EDITOR|EDITDATE|USERREMARKS|SYMBOL|EDITABLE|VISIBLE|VERSION|
|--------|------|---------|---------|----|-------------|-------------|---------|------------|-------|----------|------|--------|-----------|------|--------|-------|-------|
|306|5C8A3D4F-B590-4FF3-BD0B-2997B5818DE7|LITHDETAIL|metamorphic - unclassified|altered metamorphic rock|altered metamorphic rock||42.0||Bedrock Committee|2016-11-28|Pierre Brouillette|2023-09-18|https://github.com/NRCan/GSC-Field-Application/issues/264||Y|Y|1.8|
|308|75BA1795-6BAA-4ED5-A14B-6A10D3706E6E|LITHDETAIL|metamorphic - schist|blueschist|blueschist||44.0||Bedrock Committee|2016-11-28|Pierre Brouillette|2023-09-18|https://github.com/NRCan/GSC-Field-Application/issues/264||Y|Y|1.8|
|309|D664CA57-70A2-4353-BA32-E4C0FC5C76D1|LITHDETAIL|metamorphic - unclassified|crystalline magnesite|crystalline magnesite||46.0||Bedrock Committee|2016-11-28|Pierre Brouillette|2023-09-18|https://github.com/NRCan/GSC-Field-Application/issues/264||Y|Y|1.8|
|310|02C43138-313F-4631-94F3-95FEEFE1018C|LITHDETAIL|metamorphic - unclassified|eclogite|eclogite||47.0||Bedrock Committee|2016-11-28|Pierre Brouillette|2023-09-18|https://github.com/NRCan/GSC-Field-Application/issues/264||Y|Y|1.8|
|311|405B8FD4-185F-4FEA-8447-3236A17BCE07|LITHDETAIL|metamorphic - unclassified|garnetite|garnetite||48.0||Bedrock Committee|2016-11-28|Pierre Brouillette|2023-09-18|https://github.com/NRCan/GSC-Field-Application/issues/264||Y|Y|1.8|
|313|0C77F7C0-6DB1-4E0C-89D9-9353F1DF90D9|LITHDETAIL|metamorphic - schist|greenschist|greenschist||50.0||Bedrock Committee|2016-11-28|Pierre Brouillette|2023-09-18|https://github.com/NRCan/GSC-Field-Application/issues/264||Y|Y|1.8|
|317|54A5CECB-1C77-4F60-99F1-22F31F4E0D58|LITHDETAIL|metamorphic - schist|schist|schist||55.0||Bedrock Committee|2016-11-28|Pierre Brouillette|2023-09-18|https://github.com/NRCan/GSC-Field-Application/issues/264||Y|Y|1.8|
|318|D8BF7105-C0BF-4714-BA26-80DD3DB957E9|LITHDETAIL|metamorphic - unclassified|serpentinite|serpentinite||56.0||Bedrock Committee|2016-11-28|Pierre Brouillette|2023-09-18|https://github.com/NRCan/GSC-Field-Application/issues/264||Y|Y|1.8|
|319|FC164859-DA9D-4CA3-8847-8846FAB62B7F|LITHDETAIL|metamorphic - skarn|skarn|skarn||57.0||Bedrock Committee|2016-11-28|Pierre Brouillette|2023-09-18|https://github.com/NRCan/GSC-Field-Application/issues/264||Y|Y|1.8|
|320|1B7A9D55-ADC9-4525-8EB7-43A6E8AFA8A1|LITHDETAIL|metamorphic - unclassified|slate|slate||58.0||Bedrock Committee|2016-11-28|Pierre Brouillette|2023-09-18|https://github.com/NRCan/GSC-Field-Application/issues/264||Y|Y|1.8|
|321|28C4F8CB-BD25-4AE3-B5E9-42C0698247BD|LITHDETAIL|metamorphic - schist|sub-greenschist|sub-greenschist||59.0||Bedrock Committee|2016-11-28|Pierre Brouillette|2023-09-18|https://github.com/NRCan/GSC-Field-Application/issues/264||Y|Y|1.8|
|678|3EE20F9B-98BC-4AEB-865F-15C18F0A72A5|LITHDETAIL|tectonite - ductile|pseudotachylyte|pseudotachylyte||578.0||Bedrock Committee|2016-11-28|Pierre Brouillette|2023-09-18|https://github.com/NRCan/GSC-Field-Application/issues/264||Y|Y|1.8|
|3912|6D0A8602-FCDB-47D6-B01F-7744E2195398|LITHDETAIL|metamorphic - unclassified|calcsilicate|calcsilicate||58.1||Bedrock Committee|2016-11-28|Pierre Brouillette|2023-09-18|https://github.com/NRCan/GSC-Field-Application/issues/264||Y|Y|1.8|
|3913|725A497F-2702-4326-A855-6348A83B469A|LITHDETAIL|metamorphic - unclassified|marble|marble||216.0||Bedrock Committee|2016-11-28|Pierre Brouillette|2023-09-18|https://github.com/NRCan/GSC-Field-Application/issues/264||Y|Y|1.8|

**Comment by ghuotvez** [comment]
Amphibolite changes for some reasons couldn't be found anywhere.

- [ ] Add --> metamorphic - amphibolite	amphibolite 
- [ ] Remove -->metamorphic - schist	amphibolite schist
- [ ] Add --> metamorphic - amphibolite	amphibolite schist
