### ISSUE TITLE
Upgrade schema failure

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#267]
From end user, when converting a field book from app version 1.2 to 2.3.13.

**Comment by AMartin-MB** [comment]
Resolved in GSC Field App 2.3.18.0 (.sqlite & .zip both upgrade successfully).  No testing performed using .gpkg files.

**Comment by ghuotvez** [comment]
> Resolved in GSC Field App 2.3.18.0 (.sqlite & .zip both upgrade successfully). No testing performed using .gpkg files.

That's great!

**Comment by ghuotvez** [comment]
Will make sure it still works under version 2.4 for the upgrade to the new data model version 1.8

**Comment by ghuotvez** [comment]
Added some waiting cursor, and prevented multiple pop-up end message if database was multiple versions behind.

**Comment by ghuotvez** [comment]
Will be available in next release, version 2.4
