### ISSUE TITLE
photo form layout

### ISSUE THREAD

**Issue by jameljoseph** [NRCan/GSC-Field-Application#269]
so with the new mesa tablets, if you take a photo, the thumbnail blocks out most of the name field so you cannot see the name of the picture

**Comment by jameljoseph** [comment]
I think I fixed this, Issue with objects and the RelativePanel.Below value so shoul dbe fixed but hav eto test with Mesa3

**Comment by ghuotvez** [comment]
> I think I fixed this, Issue with objects and the RelativePanel.Below value so should be fixed but have to test with Mesa3

Nice thanks, if you could push the code I might give it a try on a mesa 3 here.

**Comment by jameljoseph** [comment]
the code was pushed a few days ago so check it out when you have time

**Comment by ghuotvez** [comment]
I've taken the latest and still it doesn't show at the proper place.

**Comment by ghuotvez** [comment]
In fact, it was a default camera setting difference. When saving the photo on a Panasonic in landscape mode, the thumbnail was fine in the form. When in portrait mode, like the default on Mesa3 then it's overlapping other components. We can reproduce this problem on the desktop by changing the orientation of the photo before saving.
