### ISSUE TITLE
Settings - Photo vs Document

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#273]
When toggling the settings to show a document form instead of a photo form, then toggling back to photo, in the field note pages the word "File" is still shown instead of "Photo".

**Comment by jameljoseph** [comment]
hey Gab, so for this, what settings are you toggling to get this error?

**Comment by ghuotvez** [comment]
> hey Gab, so for this, what settings are you toggling to get this error?

If you go in the settings>>Other tab, you'll see a toggle in there to activate the photo vs document mode.
![image](https://github.com/NRCan/GSC-Field-Application/assets/19910413/add60e62-6ffb-4c34-b2c9-7c43a1740aa5)

**Comment by jameljoseph** [comment]
So on the mesa3 i have been toggling this toggle button many times and when I toggle from default to extended and vice versa, the name same Photo every time in the field notes page that lists all the photo records

**Comment by ghuotvez** [comment]
> So on the mesa3 i have been toggling this toggle button many times and when I toggle from default to extended and vice versa, the name same Photo every time in the field notes page that lists all the photo records

Oh so in this case it's the reverse. I was always seeing File, but yours seems stock on Photo. There might be something happening with the way we're saving the setting in the local setting class, regarding that particular option.

**Comment by jameljoseph** [comment]
Ok so I am guessing the text in the headers are saved in a database.  If so why wouldnt we hard code the text value so it would never change?

**Comment by ghuotvez** [comment]
> Ok so I am guessing the text in the headers are saved in a database. If so why wouldnt we hard code the text value so it would never change?

The text is hardcoded, it's in the resource files, tagged with the name of the control, so we have an english and french version. But I agree, for now it's doing more harm then anything. We could remove this little fancy option and keep photo instead.

**Comment by jameljoseph** [comment]
ok I will look into it and see where it is.  I guess we do need code to change the wording depending on english or french so it cannot be completely hard coded.

**Comment by ghuotvez** [comment]
> ok I will look into it and see where it is. I guess we do need code to change the wording depending on english or french so it cannot be completely hard coded.

Yeah exactly.

**Comment by jameljoseph** [comment]
now I got file.  I made a new field book and it says file

**Comment by jameljoseph** [comment]
Ok so I found this:

public const string KeywordDocumentHeaderTrue = "File";
public const string KeywordDocumentHeaderFalse = "Photo";

Looks like the code below this says make the header name photo when in photo mode but file if it is in extended mode.  Do you still want this to do that?

**Comment by ghuotvez** [comment]
> Ok so I found this:
> 
> public const string KeywordDocumentHeaderTrue = "File"; public const string KeywordDocumentHeaderFalse = "Photo";
> 
> Looks like the code in FieldNotesViewModel says make the header name photo when in photo mode but file if it is in extended mode. Do you still want this to do that?

Well, yes if you can fix it, else don't spend too much time on that and make it so it's always Photo and remove the extra bits that aren't needed anymore.

**Comment by jameljoseph** [comment]
so i couldnt fix it so i made both the true and false header = photo

**Comment by ghuotvez** [comment]
80c67eed6ffc8296a4d8bd6a23d5287f59d747d8
