### ISSUE TITLE
Ajout de champs F_DOCUMENT Scale et Direction_scale

### ISSUE THREAD

**Issue by AnnickMorin** [NRCan/GSC-Field-Application#282]
Proposition de Michel:
Ajouter le champ Scale et Direction_Scale, peut être utile pour les structurologues.

![image](https://github.com/NRCan/GSC-Field-Application/assets/49729155/f0584372-bc83-4bc6-b64d-a92dcbd5d3e7)

**Comment by eygirard** [comment]
Direction_scale est étrange comme nom ou je ne comprend pas. La difficulté avec direction c'est qu'elle peut être numérique ou alphanumérique, J'auras tendance à ramener tout au numérique... à discuter

**Comment by ghuotvez** [comment]
> Direction_scale est étrange comme nom ou je ne comprend pas. La difficulté avec direction c'est qu'elle peut être numérique ou alphanumérique, J'auras tendance à ramener tout au numérique... à discuter

Annick m'avait expliqué que la direction de l'échelle était utilisé pour décrire sommairement la direction d'une structure qui est démontré par l'utilisation d'une échelle comme un crayon. L'actuel champs Direction est utilisé pour la photo même.

**Comment by ghuotvez** [comment]
We'll only add direction_scale. Usually the scale is pretty obvious on the image. It could also be quite easily extracted from a software as to which photos shows a pen or a hammer. Scale direction though, is useful since the picture will be showing a closed up outcrop.
