### ISSUE TITLE
Modification du nom du bloc Contact pour Relationship

### ISSUE THREAD

**Issue by AnnickMorin** [NRCan/GSC-Field-Application#283]
Proposition de Pierre/Louise

Modifier le nom du bloc "Contact" pour "Relationship" 

C'est 2 champs servent plus à la description de la relation entre 2 ou plusieurs unités qu'à la description d'un contact.

**Comment by ghuotvez** [comment]
@AnnickMorin Si je modifie le bloc de contact pour y ajouter des notes comme demandé ici --> https://github.com/NRCan/GSC-Field-Application/issues/254 est-ce encore pertinant de renommber le bloc au complet pour "relationship"?

**Comment by ghuotvez** [comment]
Dropped because not useful anymore since we brought back some old fields that gives more contact related information.
