### ISSUE TITLE
Field book - Activate on select

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#289]
Rather then activating the field book with a click on the checkmark in the top banner, it should be activated on a select on screen. As soon as the field book item is select a user should be able to do a quick backup for example. This is not the case for now.

**Comment by ghuotvez** [comment]
> Can now open a fieldbook by just clicking on the fieldbook. I left the open button at the top just in case but will remove it when safe to do so

Awesome thanks Jamel! Yeah we might as well leave it there. For those who were using it, they won't go searching for it.

**Comment by jameljoseph** [comment]
No problem!  It works on my end no problem
