### ISSUE TITLE
Field book upgrade - fails on older book version 1.44

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#291]
Found by a user while trying to get his older field book from version 1.2 of the application, inside the version 2.2.X.

**Comment by AMartin-MB** [comment]
To clarify, the Upgrade function works in version 2.2.59 but fails in 2.3.X.

**Comment by ghuotvez** [comment]
> To clarify, the Upgrade function works in version 2.2.59 but fails in 2.3.X.

Thanks for the clarification!
