### ISSUE TITLE
Map - Info causes app crash

### ISSUE THREAD

**Issue by AMartin-MB** [NRCan/GSC-Field-Application#292]
Using the _Info_ button on the _Map_ page causes the app to crash; Trimble T7 tablets (Win10 22H2; GSC Field App 2.3.18.0).

**Comment by jameljoseph** [comment]
I added a try catch block that gives a message of the error so that next time if the error occurs, it should give us a message before it crashes, telling us what the problem is.  On my machine and on the panasonic I cannot recreate this

**Comment by AMartin-MB** [comment]
Anything I can do to provide a log/error message?  The application crashes 100% of the time _Info_ is clicked on our Trimble T7s.

**Comment by jameljoseph** [comment]
I would say just don't click it.  I put that whole block of code in a spot where if it doesn't work, it shouldn't crash the program.  That would mean you need to download the latest code from our dev branch though.

**Comment by ghuotvez** [comment]
Well, I was already planning on getting rid of this button. It wasn't that much useful. It was planned 6 years ago to make a bit of space on a Windows phone. If this causes too much problem, let's get rid of it.

**Comment by jameljoseph** [comment]
Want me to remove this now Gab?  I agree it is useless and I will just comment it out just in case we want it later?

**Comment by jameljoseph** [comment]
Want me to remove this now Gab?  I agree it is useless and I will just comment it out just in case we want it later?

**Comment by jameljoseph** [comment]
Want me to remove this now Gab?  I agree it is useless and I will just comment it out just in case we want it later?

**Comment by jameljoseph** [comment]
fixed
