### ISSUE TITLE
Map page graphic refresh problem

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#295]
When deleting some stations in the field notes, their label graphics are still visible in the map page. A app restart is needed to erase those graphics.

Does not have any implication on the station naming though. It's only related to graphics.

**Comment by jameljoseph** [comment]
If you add a station, then delete it, and then add a new station at a different location, it will use the same station id and on the map it shows 2 spots with the same station id

**Comment by ghuotvez** [comment]
> If you add a station, then delete it, and then add a new station at a different location, it will use the same station id and on the map it shows 2 spots with the same station id

That's kind of annoying. Do you think you could have some time to fix this?

**Comment by jameljoseph** [comment]
fixed
