### ISSUE TITLE
French sample purposes

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#296]
Update the french description for sample purposes.

**Comment by akrushnisky** [comment]
Voici la liste avec la traduction des termes en français:

[SampPurposes_20230808_FR.xlsx](https://github.com/NRCan/GSC-Field-Application/files/12312749/SampPurposes_20230808_FR.xlsx)

**Comment by ghuotvez** [comment]
Done and will be available in next version under new schema 1.8 later one this year.
