### ISSUE TITLE
Station, Waypoint,  mettre à jour le stationid_name

### ISSUE THREAD

**Issue by AnnickMorin** [NRCan/GSC-Field-Application#302]
Hello 
Lorsqu'un utilisateur dans le formulaire station, sélectionne observation: waypoint,  le numéro de stationid_name ne se met pas à jour.
Le numéro devrait être en format waypoint  exemple="waypointHUBM001".

Soulever par Michel H.

**Comment by jameljoseph** [comment]
Gab, since we have waypoint as a separate button on the map page, we should remove waypoint from the list of observations when someone selects station.

**Comment by ghuotvez** [comment]
Rather then transforming the whole thing into a waypoint form, we did remove it from the station form list. We'll keep waypoint in their own spot, which is a dedicated button.

**Comment by AnnickMorin** [comment]
Cependant lorsqu'un utilisateur utilise ManualXY mais il veut que ce soit un waypoint et non une station. Une suggestion:  est-ce possible que le bouton ManualXY ait un option à cocher pour indiquer si c'est un waypoint ou une station?
J'ai créé ce ticket parce que l'utilisateur avait les coordonnées mais ne voulait pas que ce soit une station. Il a utilisé le chemin détourné de passer par le formulaire de la station pour la transformer en waypoint.

**Comment by ghuotvez** [comment]
> Cependant lorsqu'un utilisateur utilise ManualXY mais il veut que ce soit un waypoint et non une station. Une suggestion: est-ce possible que le bouton ManualXY ait un option à cocher pour indiquer si c'est un waypoint ou une station? J'ai créé ce ticket parce que l'utilisateur avait les coordonnées mais ne voulait pas que ce soit une station. Il a utilisé le chemin détourné de passer par le formulaire de la station pour la transformer en waypoint.

Ahh ok je comprends mieux ce que ça voulait dire.
