### ISSUE TITLE
Can't take floating point numbers in easting northing

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#303]
Adding decimals to easting northing does nothing.

**Comment by jameljoseph** [comment]
I noticed the 2 text boxes act very weird.  For easting, the decimal will go to the very front if the text box stays the same size.  If you  add like 7 digits and the box gets bigger, then the decimal goes in the right spot

**Comment by ghuotvez** [comment]
> I noticed the 2 text boxes act very weird. For easting, the decimal will go to the very front if the text box stays the same size. If you add like 7 digits and the box gets bigger, then the decimal goes in the right spot

Hum weird. I know that I did code something that prevents user from entering decimals in there because in my own opinion it's quite useless and it'll always be smaller then any relative errors like data coming from a GPS or  trying to take a coordinate from a paper map with a compass. But one geologist would like to add the exact and very very precise coordinate of drill hole taken by the drill company. 

The field in the database can take those decimals, it's really a matter of removing what I added as an extra to have some round integers metric coordinates.

**Comment by jameljoseph** [comment]
Well I checked northing, if I enter 1 to 7 digits, then when I hit decimal it goes to the front.  If I put in 8 digits, the box gets bigger, and then when I click the decimal it goes in the right spot

**Comment by ghuotvez** [comment]
> Well I checked northing, if I enter 1 to 7 digits, then when I hit decimal it goes to the front. If I put in 8 digits, the box gets bigger, and then when I click the decimal it goes in the right spot

Yeah, it's a bit clunky. I also added some extra validation on the number of digits, so the user doesn't mix easting and northing together since they only have 1 digit of difference.

**Comment by jameljoseph** [comment]
I noticed you have TextChanging="LocationEasting_TextChanged" but when I go to definition it is blank.  I guess we do not need that.

**Comment by ghuotvez** [comment]
> I noticed you have TextChanging="LocationEasting_TextChanged" but when I go to definition it is blank. I guess we do not need that.

Maybe it's in the viewmodel rather then the xaml.cs?

**Comment by ghuotvez** [comment]
it could be directly in a get/set property of the model itself too or inside a converter class or inside a get/set property inside the viewmodel (I would bet on the later).

**Comment by jameljoseph** [comment]
> > I noticed you have TextChanging="LocationEasting_TextChanged" but when I go to definition it is blank. I guess we do not need that.
> 
> Maybe it's in the viewmodel rather then the xaml.cs?

I checked and i didnt see it there.  I see the definition of locationeasting but the locationeasting_textchanged event is not there.

**Comment by jameljoseph** [comment]
Ok so it works but the easting and northing is not being saved to the database so I will open a new bug
