### ISSUE TITLE
Easting and Northing values do not save to db

### ISSUE THREAD

**Issue by jameljoseph** [NRCan/GSC-Field-Application#304]
So when you enter a station using XY coordinates, you can now enter decimal points to the value.  The issue here is that when you save the station, the Easting and Northing values will only save if there is no decimal in it.  

The issue I believe is with this line of code:

this.LocationEasting.Text = east.ToString();  

This line of code has caused a couple issues but I will try to find a way around it

**Comment by ghuotvez** [comment]
Related to #303

**Comment by jameljoseph** [comment]
fixed
