### ISSUE TITLE
EarthMat form:  Contact_Note

### ISSUE THREAD

**Issue by jameljoseph** [NRCan/GSC-Field-Application#307]
So when I have a pre-existing record in earth materials and I pick a new rock type and hit save, I get an error saying:

no such column: Contact_Note.

When I try to create a new Earth Material and save it I get:

table F_Earth_Material has no column named Contact_Note

**Comment by jameljoseph** [comment]
Do you want me to remove all code related to Contact_Note Gab?

**Comment by ghuotvez** [comment]
Oh, that's happening because you have an older field book. Create a new one and it should work fine. That's one change coming from the new version 1.8.
