### ISSUE TITLE
add a calendar to the date field in drillhole form

### ISSUE THREAD

**Issue by jameljoseph** [NRCan/GSC-Field-Application#316]
As I was testing the drillhole form, I figured we should have a set format for date so we should have a calendar date pick option.

**Comment by jameljoseph** [comment]
Added a calendar date picker to the textbox and will format it to month, day, year. so it is the same format for everyone.  If you want to change it to another format let me know.

**Comment by ghuotvez** [comment]
Hum, yeah that's what I added first, but the geologist told me something it's old drill cores and they don't have the whole date or it's inverted, english vs french. So I removed it to get a free text box.

**Comment by jameljoseph** [comment]
oh ok.  Well I added it below the textbox and connected it to it so 2 options?

**Comment by ghuotvez** [comment]
It's more for an informative field then a proper date field in which you would get a query in the database, like I want all drill holes younger then X.

**Comment by ghuotvez** [comment]
> oh ok. Well I added it below the textbox and connected it to it so 2 options?

Haha ok. Hum let it there for now, we'll see how it fits well.

**Comment by jameljoseph** [comment]
yeah check it out.

**Comment by ghuotvez** [comment]
- [ ] Alright, I took a look at it. Could you make the original text box as wide as the calendar control?

- [ ] Then, when I enter a random half date like 2013-01, save, then reload, change to something from the calendar like 2023-12-14, save then reload, it's not being saved for some reasons.

**Comment by jameljoseph** [comment]
So I figured out why.  the textbox the date is going to needs focus.  I will add it

**Comment by ghuotvez** [comment]
@jameljoseph thanks for the work it all works fine now. I've made a small change in the date format so it matches the date capture elsewhere in the application.
