### ISSUE TITLE
Modification dictionnaire mica schist

### ISSUE THREAD

**Issue by annmorin** [NRCan/GSC-Field-Application#318]
Hello 
metasedimentary, siliciclastic, mica schist est manquant dans l'application

Je crois qu'il devrait être là. Il est présent dans la fodr. Est-ce que tu saurais pourquoi il n'est plus là.

![image](https://github.com/NRCan/GSC-Field-Application/assets/133264523/ff816fb9-2c9e-4d01-8db2-a032b03778ad)

merci beaucoup

**Comment by ghuotvez** [comment]
Je l'ai ajouté à nouveau, ce sera disponible dans la prochaine version.
