### ISSUE TITLE
changement de nom de roche, certaines boites se vident

### ISSUE THREAD

**Issue by AnnickMorin** [NRCan/GSC-Field-Application#327]
Hello,

Lorsque le formulaire de Earthmaterial est rempli et que l'on veut changer le nom de la roche, les boites Texture/structure, grain crystal Size, bedding thickness et deformation fabric se vident.

J'aurais tendance à ne pas effacer l'information à l'intérieur de ces boites lorsque le nom de la roche est modifié.

**Comment by ghuotvez** [comment]
Le terme a seulement été modifié? Dans ce cas, c'est mon code qui ne se fit pas à la bonne valeur donc. J'imagine que ma requête sql pour sortir les text/struc se base sur la description plutôt que le code.

Merci pour la trouvaille!

**Comment by ghuotvez** [comment]
Cherry-pick to dev-app.
