### ISSUE TITLE
Quick Backup causes app crash if Field Book contains photos

### ISSUE THREAD

**Issue by AMartin-MB** [NRCan/GSC-Field-Application#336]
App crashes if user saves a Quick Backup if the Field Book contains a photo.  Removal of photos from Field Book allows the Quick Backup to complete successfully.

**Comment by ghuotvez** [comment]
Something's wrong with the zip archiving code. I've changed something so it handles big zips over 2Go, which was a previous bug. All testing locally worked fine. I'll try and reproduce this on some other tablets. Thanks for pointing it out.

**Comment by ghuotvez** [comment]
Happened after trying to fix #333.

Now resolved for both current issue and #333.
