### ISSUE TITLE
Complete Backup causes app crash

### ISSUE THREAD

**Issue by AMartin-MB** [NRCan/GSC-Field-Application#337]
Cannot save a Complete Backup (.zip).  App crashes after user clicks: Complete Backup > Save.  Behaviour seems unrelated to contents of Field Book.  Tried removing photos, TPKs or removing stations.  Behaviour remains consistent (0% success rate).

**Comment by ghuotvez** [comment]
Happened after trying to fix #333.

Now resolved for both current issue and #333.
