### ISSUE TITLE
structure form, convert azimuth, dip, symang to number field

### ISSUE THREAD

**Issue by jameljoseph** [NRCan/GSC-Field-Application#338]
So I am curious as to why the Azimuth, Dip, and symang fields in the structure table are text fields?  We are attempting to use a stereograph extension in ArcMap and it requires those 3 fields to be numeral, not text.

**Comment by ghuotvez** [comment]
Could you try opening it in QGIS? Worst case, we do have a qgis script that converts the geopackage to a file geodatabase with FME. Send me the data and I'll convert it.

**Comment by jameljoseph** [comment]
Hey Gab, yes I see that now.  When I converted the gpkg to geodb, it converted those 3 fields to text but the other fields that were integer stayed as integer.  No worries then thanks Gab.
