### ISSUE TITLE
structure table plot to map checkbox?

### ISSUE THREAD

**Issue by jameljoseph** [NRCan/GSC-Field-Application#339]
So we are going over the structure table fields in the geodb and the app and saw there there is no way for a geologist to specify in the field if a measurement is representative of the area and should be plotted on the map.  Jim and Nathan seem to think this would be a good feature to have.  Maybe make it a checkbox.

**Comment by jameljoseph** [comment]
added PlotToMap to the database in schema_19 branch, will work on code to add checkbox now

**Comment by ghuotvez** [comment]
Will need this code in version 3 along the new .gpkg that has this new field.

@jameljoseph did you added some code to make the check box value saved in the DB then reloaded on edit? I don't see it in the commit.

**Comment by ghuotvez** [comment]
@jameljoseph brought your changes to version 3.
