### ISSUE TITLE
Duplicate field books appear after editing a field book

### ISSUE THREAD

**Issue by AMartin-MB** [NRCan/GSC-Field-Application#345]
Editing an existing field book and saving the changes causes the field books page to display duplicates of all field books.
Closing and reopening the app removes the duplicates.

In version 2.3.18, if a user deletes a duplicate field book, both field books of the same name are deleted and the app crashes.  The app continues to crash every time the user tries to create a new field book (+ icon) after the initial crash.

In version 2.4.1, deleting a duplicate field book, deletes both field books of the same name.  No crashes occur.  Users can continue to create new field books without issue.

**Comment by ghuotvez** [comment]
Can't reproduce for now, I'll make more testing on actual devices this week.

**Comment by ghuotvez** [comment]
> Can't reproduce for now, I'll make more testing on actual devices this week.

I mean can't reproduce with the dev branch, something might have fixed it from other issue fixes.

**Comment by ghuotvez** [comment]
Alright, I was able to reproduce the problem on a Panasonic. That gives me some hints.
