### ISSUE TITLE
"Backup" label on Navigation pane to be clarified?

### ISSUE THREAD

**Issue by KazShimamura-GSC** [NRCan/GSC-Field-Application#40]
The "Backup" label on the Navigation pane is for quick backup of only the geologists field data's observations and measurements, and does not backup any photo's taken within the device or the TPK.  Full backup is located in the FieldBook Project page's Full Backup menu item. However, the user may not immediately know that by looking at the "Backup" label in the Nav Pane. Should it be relabeled as "Quick backup"? or something else that's helps differentiate between this and the full backp?

**Comment by ghuotvez** [comment]
It will backup the daily photos taken with the tablet itself.

I'm in for Quick backup though, it does align with the quick buttons in the map page, on the wording I mean (see our Ontology document) . And I did get some comments from end user that didn't fully understand the difference between backup and full backup.

New wording --> Quick backup and Complete backup.
