### ISSUE TITLE
Lithology semantic zoom

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#41]
Instead of duplicating first lithology order beside all second level, add an indentation instead?

@AnnickMorin on behalf of Michel.

hydrothermal
hydrotherm - void fill

could look like

hydrothermal
-----void fill

**Comment by ghuotvez** [comment]
I did some changes in the code to have a better look at how it would render on screen. Not really good actually. We can remove the duplicate words and put in some tab spaces in first level, but it then reflects on the zoomed in list. Navigating through is more detail list without having the duplicated word makes it harder to track where we are. 

After some more thoughts and discussion with @AnnickMorin  we'll keep original method since it makes more sense once we're in the fully detail value lists. This is due to title/header keeping it's string from zoomed out to zoomed in. There might be ways of customizing the semantic zoom control and make it look better, but we need to prioritize our times. So this issue fix won't be merged into main branch for now.

## With quick fix
![image](https://user-images.githubusercontent.com/19910413/118304653-f0ae4d80-b4b4-11eb-877d-d1561208fa51.png)

## Without quick fix
![image](https://user-images.githubusercontent.com/19910413/118305311-c4df9780-b4b5-11eb-8f6d-b02510220e69.png)

**Comment by jameljoseph** [comment]
I like without the quick fix from a functional point of view.  It is just nice to see the 3 levels of rock type together and it might be re-assuring to the geologist to see everything.

**Comment by ghuotvez** [comment]
> I like without the quick fix from a functional point of view. It is just nice to see the 3 levels of rock type together and it might be re-assuring to the geologist to see everything.

Alright thanks Jamel!. I guess we won't be keeping the implementation then. Not good enough.
