### ISSUE TITLE
Bd sqlite dans le menu Layers

### ISSUE THREAD

**Issue by AnnickMorin** [NRCan/GSC-Field-Application#49]
Lorsque je load une bd sql lite pour visualiser dans un projet déja existant, impossible de la tourner à "off" dans le menu "Layers". Je dois l'effacer pour qu'elle disparaisse.

**Comment by saralizj** [comment]
Hi there!  I have a similar issue, but it's even more complex:
1) anytime i try to load a .sqlite file, it shows up at least three, sometimes four times in the layers and does not have a name shown, so there is no way to know which layer is which;
2) once loaded, i get the following error:
![sqlite_load_error](https://user-images.githubusercontent.com/23459408/116585341-dbe98b80-a8f2-11eb-8108-6ae38e0268f6.png)

3) cannot delete the layers (all three or four versions), and trying to delete them crashes the app.  There is no recovery (opens again with error #2, and crashes.  Only solution seems to be to start a new field notebook.  

Help please!

**Comment by ghuotvez** [comment]
Hi!

That's an old issue that was supposed to be fixed. It might be linked to your recent issue #84 with the upgrade button that created a bunch of unusable databases. There is a way of doing a hard reset on your app, but you'll lose any data. If it's not a problem for you try to go in settings --> about page --> double tap on the gsc logo (upper right). Factory reset is hidden there. That's a quick way of getting a new app ready for a summer field camp without going through all fieldbook and delete them all one by one and clean after whoever used the tablet before.

![image](https://user-images.githubusercontent.com/19910413/116593766-73e57600-a8ef-11eb-9f4b-b491cfb81f40.png)

If it's not a good solution we could find another way of doing this without getting the big guns out.

**Comment by saralizj** [comment]
Ah, this answers my question that i just posted on the other issue.  I'll give this a try!

**Comment by ghuotvez** [comment]
From @saralizj 

> really, this red error comes up again and again.  This time, while writing this email, it crashed after I pushed the layers button.  Upon reopening the field book, I am immediately presented with the error, as well as three duplicates of the two layers I’ve loaded: a previous project’s .sqlite data and a very simple .tpk. My two points show (with no details, as reported in 5), but my base imagery .tpk does not show.  I cannot delete the extra copies of the layers – any attempt to push the trash just crashes the app.  This basically forces me to open a new field notebook and start a new app test.

**Comment by ghuotvez** [comment]
While doing some other testing I was able to reproduce this problem. Wanted to add an extra tpk, crashed the app, open it up again and I see 3 of them were added. Then I get your above message error.
