### ISSUE TITLE
Test ink option for free text boxes

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#60]
For note fields, test the ink option and also to conversion to text within the ink box.

**Comment by jameljoseph** [comment]
I will tackle this one next Gab

**Comment by jameljoseph** [comment]
Working on it now

**Comment by jameljoseph** [comment]
Ok so I played with the ink option with both hand and pen recognition both in the app and outside the app.  We just have to make sure we go into:

In settings, go to devices --> pen and windows ink.  

In there we can select the font used, but more importantly, check off the box that says write in the handwriting panel with your fingertip.  I have practiced both with the pen and with my finger and both work well.

I believe all the text box settings are good to go now.  There is a voice option too Gab, should we look into that?

**Comment by ghuotvez** [comment]
Oh yeah sure, why not, that could good. Maybe some would be interested.

**Comment by jameljoseph** [comment]
Ok sure thing.  I will test that as well.
