### ISSUE TITLE
Tutorial videos - youtube

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#62]
Remake the tutorial videos with the latest UI and make them available with a youtube account rather then the NRTube website.<

Start with the intro version first and see if there is time for the installation. When times permit it, continue with the remaining ones.

**Comment by ghuotvez** [comment]
It's all done and available in the wiki. Thanks again Robert!

**Comment by rcocking** [comment]
Always happy to work with you guys. ☺
