### ISSUE TITLE
Windows 10 compatibilities with pen

### ISSUE THREAD

**Issue by eygirard** [NRCan/GSC-Field-Application#69]
I test the version 170 with Windows 10 1809 and it seems to work. To resolve the problem for Pen (it's not work since a while) you must install https://pc-dl.panasonic.co.jp/dl/docs/077277 select 
12 - sysifman_v15.02l15m00_d20184358.exe for table older than 2106 (model FZ-M1C) or 13 - sysifman_v15.04l17m00_d20184357.exe(18.1 mb) for tablet 2017 and newer (FZ-M1F).

A newer version of windows 10 1909 is available since december 11 2019 and should be test.

**Comment by jameljoseph** [comment]
How can we tell if our tablets are FZ-M1C or M1F?

**Comment by ghuotvez** [comment]
Good question, I think it's behind the battery on the sticker there.

**Comment by eygirard** [comment]
Yes it is, under the battery

**Comment by jameljoseph** [comment]
Ok thanks.  I have 1 of each!!

**Comment by ghuotvez** [comment]
This works fine now with the latest W10 version, 21H2. Pencils are now all working.
