### ISSUE TITLE
Format field on Structure record

### ISSUE THREAD

**Issue by rcocking** [NRCan/GSC-Field-Application#70]
Hi Gab,

I may have found a small issue. I added a structure record and noticed the red box. Went in to edit it and could not set the format, none of the options showed. v1.0.170.0.

![image](https://user-images.githubusercontent.com/52049001/80758781-08ee3d00-8aeb-11ea-8f6f-885ffe9e77c9.png)

**Comment by ghuotvez** [comment]
@rcocking from your print screen it seems you haven't selected an actual structure. That might have been why it wasn't working.

Still I have found a little glitch with first structure taken which can't be related to another one, which pushed invalid. I fixed that.
