### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by rcocking** [NRCan/GSC-Field-Application#73]
What does this button do? "Update field book database schema" is a bit vague. 

When I clicking on this, the app crashed. When I restarted, there was a duplicate of the field book, but without the project information. Attempts to edit the duplicate resulted in a crash. 

Deletion of the duplicate field book also failed. It asks if I am sure, then it asks if I want to backup, but the field book is not removed.

**Comment by ghuotvez** [comment]
First release works on 2004, this should be fixed now. :)
