### ISSUE TITLE
Install not working under Build 1909

### ISSUE THREAD

**Issue by rcocking** [NRCan/GSC-Field-Application#74]
Hello,

Went into developer mode, installed the certificate successfully, installed the .ps1 and got this error. It also does not work in side-load mode.

![image](https://user-images.githubusercontent.com/52049001/82592906-77587500-9b56-11ea-8b3e-32195c21f741.png)

**Comment by ghuotvez** [comment]
That was due to certificate issue. This is fixed with first release.

**Comment by rcocking** [comment]
I can confirm the certificate issue is solved!
