### ISSUE TITLE
Certficate problems

### ISSUE THREAD

**Issue by rcocking** [NRCan/GSC-Field-Application#75]
Hello,

I was just able to restore my B1809 VM and I installed the certificate and app. First, I shifted into Developer mode. Then the certificate installed successfully, however, when I installed the Add-AppDevPackage.ps1 file within Powershell, I got the following error message relating to the certificate being expired:

![certificate_error](https://user-images.githubusercontent.com/52049001/93645575-27c96f00-f9b9-11ea-9ecf-fab993b7491b.png)

I get the same error in my B1909 VM, so I assume that this is a universal error that will prevent any field app installation.

I tried changing the clock in my VM as a workaround, but it kept resetting my change back to the current time. :(

Thanks!
Rob

**Comment by ghuotvez** [comment]
Fixed for first release
