### ISSUE TITLE
No powershell

### ISSUE THREAD

**Issue by rcocking** [NRCan/GSC-Field-Application#78]
I was able to uninstall the older version of the GSCFA on the tablet sent to me by Etienne. When I right-click on the .cer or .ps1 file I only able to see open, cut, copy, delete and properties options. There is no option to install the certificate or to use Powershell to run the .ps1 file. The Powershell is set up the same as for Gabriel (to use Notepad). The tablet is definitely in developer mode.

The tablet seems to have some odd customizations. I am a little tempted to reinstall the OS. What do you think?

**Comment by ghuotvez** [comment]
Yeah installing latest os or reinstalling might be a good idea. I wonder if you got one of those tablets. I know there was one at the lab that I wasn't able to upgrade OS, see issue https://github.com/NRCan/GSC-Field-Application/issues/48 . But that was a panasonic tablet from a geologist, his own. I hope @eygirard didn't sent you Michel's tablet haha.

**Comment by rcocking** [comment]
I had decided to reinstall the OS. The tablet has an asset tag (A130021), so it probably isn't Michel's. :)

**Comment by rcocking** [comment]
I did some googling around and saw that to reinstall the OS you needed to DL a 4MB program on the tablet. Is there a different or easier method to reinstall the OS?

**Comment by ghuotvez** [comment]
you could try a hard reset, but then you'll revert to some really old version

**Comment by rcocking** [comment]
As long as it doesn't revert to Win7. :)

**Comment by ghuotvez** [comment]
> As long as it doesn't revert to Win7. :)

yeah that would be really bad haha but with an id starting with 13 I wouldn't be surprised... you might want to ask Étienne before doing it for real. He might have more info on what year it was bought.

**Comment by ghuotvez** [comment]
Could you try locating powershell from within the tablet? You should find it here
C:\Windows\System32\WindowsPowerShell\v1.0 --> powershell.exe

Then you could try to launch an installation by opening command prompt as an admin, then

**1. Inside command prompt window, navigate to folder containing the install file.**
```
cd C:\Users\gabri\Downloads\GSCFieldApp_1.0.0.0_x64_Debug_Test\GSCFieldApp_1.0.0.0_x64_Debug_Test
```
**2. Install by calling powershell with some special arguments**
```
Powershell.exe -executionpolicy remotesigned -File "Install.ps1"
```
**3. Then you should see in command prompt what we usually see in powershell**

```
Voulez-vous exécuter le logiciel de cet éditeur non approuvé ?
Le fichier
C:\Users\gabri\Downloads\GSCFieldApp_1.0.0.0_x64_Debug_Test\GSCFieldApp_1.0.0.0_x6
4_Debug_Test\TelemetryDependencies\LogSideloadingTelemetry.ps1 est publié par
CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
et n'est pas approuvé sur votre système. N'exécutez que des scripts provenant
d'éditeurs approuvés.
[M] Ne jamais exécuter  [N] Ne pas exécuter  [O] Exécuter une fois
[T] Toujours exécuter[?] Aide (la valeur par défaut est « N ») : T
Package trouvé : C:\Users\gabri\Downloads\GSCFieldApp_1.0.0.0_x64_Debug_Test\GSCFieldApp_1.0.0.0_x64_Debug_Test\GSCFieldApp_1.0.0.0_x64_Debug.msix

Installation de l'application…
Package(s) de dépendance trouvé(s) :
C:\Users\gabri\Downloads\GSCFieldApp_1.0.0.0_x64_Debug_Test\GSCFieldApp_1.0.0.0_x64_Debug_Test\Dependencies\x86\Microsoft.NET.CoreFramework.Debug.2.2.appx
C:\Users\gabri\Downloads\GSCFieldApp_1.0.0.0_x64_Debug_Test\GSCFieldApp_1.0.0.0_x64_Debug_Test\Dependencies\x86\Microsoft.NET.CoreRuntime.2.2.appx
C:\Users\gabri\Downloads\GSCFieldApp_1.0.0.0_x64_Debug_Test\GSCFieldApp_1.0.0.0_x64_Debug_Test\Dependencies\x86\Microsoft.VCLibs.x86.Debug.14.00.appx
C:\Users\gabri\Downloads\GSCFieldApp_1.0.0.0_x64_Debug_Test\GSCFieldApp_1.0.0.0_x64_Debug_Test\Dependencies\x64\Microsoft.NET.CoreFramework.Debug.2.2.appx
C:\Users\gabri\Downloads\GSCFieldApp_1.0.0.0_x64_Debug_Test\GSCFieldApp_1.0.0.0_x64_Debug_Test\Dependencies\x64\Microsoft.NET.CoreRuntime.2.2.appx
C:\Users\gabri\Downloads\GSCFieldApp_1.0.0.0_x64_Debug_Test\GSCFieldApp_1.0.0.0_x64_Debug_Test\Dependencies\x64\Microsoft.VCLibs.x64.Debug.14.00.appx

Opération réussie : votre application a été correctement installée.
Cliquez sur Entrée pour continuer...:
```
Sorry it's in french...

**Comment by rcocking** [comment]
Hi Gab,

This worked! I got a warning about “Before installing this app, you need to do the following: - Install the signing certificate,” which it automatically installed anyway.

Thanks very much for the assistance. Shall I add this to the Wiki on GitHub?

Cheers,
Rob

**Comment by ghuotvez** [comment]
Yes!

Sure, really good suggestion! You could edit the installation guide and add this little trick to it. Or do a complete install section on wiki with links to the user guide and more information like this trick.
