### ISSUE TITLE
User Guide links broken

### ISSUE THREAD

**Issue by saralizj** [NRCan/GSC-Field-Application#81]
Hi there!  Can you please check the link to the app's user guide?  I cannot get it to load for me on any browser (although it could still be my network)..

https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll?func=ll&objaction=overview&objid=48611029

Thank you!

**Comment by ghuotvez** [comment]
> Hi there! Can you please check the link to the app's user guide? I cannot get it to load for me on any browser (although it could still be my network)..
> 
> https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll?func=ll&objaction=overview&objid=48611029
> 
> Thank you!

Hi @saralizj !

Sorry about this one,  we forgot it was on an internal network link. We'll add a document folder within the project and send most of our documents in there. I'll keep you posted.

Cheers,

**Comment by saralizj** [comment]
That would be fantastic, thank you!

**Comment by ghuotvez** [comment]
Here it is: https://github.com/NRCan/GSC-Field-Application/tree/master/Documents 

Enjoy! :)
