### ISSUE TITLE
Certificate issue on install

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#83]
Seems like the install certificate fails. I guess it's expired.

Will need to find another dev environment. The server holding the VM where the code was just die yesterday...

Will need to repackage and release again.

**Comment by jameljoseph** [comment]
Any luck with this Gab?

**Comment by ghuotvez** [comment]
> Any luck with this Gab?

Yes and no. I haven't found the time to finalize the recreation of the coding environment on my laptop to get this right. It might wait for beginning of April.

You could try it out if you want, you'll need to sign with your own name, which comes from our entrust key. You could grab the latest code from master branch, then in package manifest try to sign by yourself. Make sure to have logged in entrust before. You should get a pop-up window with an option to select your own certificate. That should do it. Then repackaging it should solve this problem for another year....it's been a temp solution since the start of the project....

**Comment by jameljoseph** [comment]
Ok I will give it a shot!!  I have looked at code a lot and I cant get anything working so I will try the certificate!!

**Comment by ghuotvez** [comment]
> Ok I will give it a shot!! I have looked at code a lot and I cant get anything working so I will try the certificate!!

Alright good :) thanks!
