### ISSUE TITLE
Upgrade option generates uneditable field notebook copies that cannot be deleted

### ISSUE THREAD

**Issue by saralizj** [NRCan/GSC-Field-Application#84]
Hi there -- for background, the Geological Survey of NL is hoping to use this app during our summer fieldwork season, so we are trying our hardest to test it inside and out.  We are using the app on Panasonic FZ-G1 Toughpad tablets with W10 pro.  Our build shows up as 19041.928... but I don't know if that means anything.

When pressing the Upgrade option on the tablet today, it closes the app.  When i reopen, there is a new field notebook added.  This notebook contains whatever information was open in the previously used notebook, but the set-up information (person, initials, etc) are empty.  I cannot edit the notebook's information -- it crashes the app. I cannot delete the new mystery notebook either. I now have three copies of these ghost notebooks that cannot be deleted.

**Comment by ghuotvez** [comment]
> Hi there -- for background, the Geological Survey of NL is hoping to use this app during our summer fieldwork season, so we are trying our hardest to test it inside and out. We are using the app on Panasonic FZ-G1 Toughpad tablets with W10 pro. Our build shows up as 19041.928... but I don't know if that means anything.
> 
> When pressing the Upgrade option on the tablet today, it closes the app. When i reopen, there is a new field notebook added. This notebook contains whatever information was open in the previously used notebook, but the set-up information (person, initials, etc) are empty. I cannot edit the notebook's information -- it crashes the app. I cannot delete the new mystery notebook either. I now have three copies of these ghost notebooks that cannot be deleted.

Hi!

That's a nice setup you got. 

The upgrade button is usually meant to be used when there is an update on the database schema itself, like new fields or new scientific language values for instance. So it'll grab the current selected fieldbook and create a new "enhanced" copy of it, so nothing is deleted. I guess that upgrading an actual latest schema fails badly. It should have mentioned you that you already have the latest and nothing more is needed. For now I suggest to only create a new fieldbook with the + icon and navigate to map page.  

I'll tag this issue as a bug, since it shouldn't fail on you like that.

**Comment by saralizj** [comment]
Breaking things is my specialty!  Also pushing all of the buttons just to see what they do... hence this issue.  Any idea how we might go about deleting those empty copies? And related to that, where would I find the actual data stored on the device?  I can't seem to find the data -- but thought clearing out the whole cache might resolve the extra empty notebooks issue, since we are only testing for the moment and don't need to save any of the test data permanently.

**Comment by ghuotvez** [comment]
The data is hidden somewhere deep within the device for security reasons, inherent to how the app is built. This is a default with Window 10 app under Universal Windows Platform. Basically the factory reset shown in #49 will delete them all for you without the possible headache of deleting other apps data.

**Comment by saralizj** [comment]
Reset worked -- that's a breeze!

**Comment by ghuotvez** [comment]
Good news :)
