### ISSUE TITLE
Advertise map page projection

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#85]
@saralizj
> Any way to know what projection the app is using for your data?  I saw a note somewhere that data layers must be added in the same project as the app, but what is that? EPSG 4326?

**Comment by ghuotvez** [comment]
Maybe we could add WGS84 below accuracy? 

![image](https://user-images.githubusercontent.com/19910413/127538194-7510ee4f-6f32-4312-9482-dc2fad03d4ae.png)

**Comment by jameljoseph** [comment]
Im working on this one now Gab

**Comment by jameljoseph** [comment]
Hey Gab, so I was playing with some classes with no luck getting the projection to show up, but then I was wondering, where do we specify projection in a project or is it default WGS 84 and doesn't ever change?

**Comment by ghuotvez** [comment]
Good question. 
It's defaulting to WGS84 because we're telling user to setup the background .tpk to be in WGS84. That was to simplify the code back when we were building the whole thing.

So, when creating the map page, we first create a Map object that we init with whatever is set in the tpk.
https://github.com/NRCan/GSC-Field-Application/blob/3fade1e938a9185fb11aa6654bff1a260c039e0a/GSCFieldApp/ViewModels/MapPageViewModel.cs#L2183

You could get a read from Map.SpatialReference property, or in our case, the esriMap variable.

**Comment by jameljoseph** [comment]
ok thanks, I was looking at Windows.Devices.Geolocation but will check out ESRIs classes.  Thanks
