### ISSUE TITLE
Zoom to data extent or to some initial scale

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#86]
@saralizj

> Any way to have the app zoom in to the extent of your data after you load data, or at least near to where you are?  When adding a test tile of small coverage area, it’s sometimes hard to locate the data because the original extent is so large

**Comment by jameljoseph** [comment]
Working on this, haven't gotten it to work yet!

**Comment by jameljoseph** [comment]
I have the zoom buttons working that zoom to the extent of each loaded tpk.  Testing on tablets shortly
