### ISSUE TITLE
Map page - have a way to switch dd and utm 

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#87]
@saralizj

>Possible to change the coordinate display to decimal degrees or UTM?  UTM would be most useful for field traverse, but DD is easier for my brain to comprehend, and also to enter into GIS apps during testing to check location accuracy.  Even better – possible to switch up how coordinate are displayed? 

No impact on location on a new record save, only for visual in upper left corner. We might want to throw that option in the settings.

**Comment by ghuotvez** [comment]
can be linked to #85

**Comment by ghuotvez** [comment]
Will be postponed for another version for now. We'll keep in line though.

**Comment by jameljoseph** [comment]
I have DD and DMS working, but not UTM so I committed the code in dev-app and will work on something else

**Comment by ghuotvez** [comment]
It's a good starting point!

**Comment by jameljoseph** [comment]
have to test it more but seems to work for me

**Comment by ghuotvez** [comment]
@jameljoseph it works great, thanks! 

I'll apply so change on the labels and add some french.
