### ISSUE TITLE
Application update, previous field books lost?

### ISSUE THREAD

**Issue by saralizj** [NRCan/GSC-Field-Application#92]
More of a question than an issue, per se, but when I updated to the latest version, my active field books disappeared.  Is there a way to retrieve them, or would a user need to remember to back up their data before updating the app?  I remember you said the data were not accessible via windows explorer, so I'm assuming the update erased old data? [I was only testing, so no important data is lost, just mainly curious about best practices for this operation in the future.] Thanks!

**Comment by ghuotvez** [comment]
Oh that shouldn't have happened, but thinking about this I guess it was bound to happen. The thing is I had to update the certificate used to install the package. It's good only for 1 year... then what happens is that it gets installed with a different "internal" id, I probably changed it without knowing. Which made it seems like it wiped your field books but they are still there.

C:\Users\{your_user_loggin}\AppData\Local\Packages 

AppData folder is a hidden one, you'll need to make them visible. Then in packages folder you'll see a tons of stuff. Look for folder starting with gscfieldapp. You should see 2 of them, the first install and the second one.

In everyday life any new app update shouldn't create a new folder and make it look like you lost your field books.

I've been in touch with IT here for years trying to get a permanent certificate for the app so we're not bound to this self-signing thing every year...

**Comment by saralizj** [comment]
Ah, no worries! I'll look for the data at the file path you specified --
super useful information. Thanks!

**Comment by ghuotvez** [comment]
I'm aiming for this https://docs.microsoft.com/en-us/windows/msix/desktop/sign-with-akv-cert but still waiting for answers from my cloud team.

**Comment by ghuotvez** [comment]
This bug wouldn't be a problem if the application would be on the windows store, unfortunately it is not.  From this issue https://stackoverflow.com/questions/50830239/updating-uwp-sideloaded-apps it seems like it won't be fixed either. Since Microsoft have dropped UWP applications in a whole, we'll likely won't see any development about it.

Won't fix with current framework.
