### ISSUE TITLE
F_EARTHMATERIAL - modtext/modstruc

### ISSUE THREAD

**Issue by ghuotvez** [NRCan/GSC-Field-Application#96]
- Merge those two field to TEXTSTRUC (this field name was used in FieldLog and first versions of Ganfeld).
- Wait for new picklist from Pierre B. 
- Add a searchable textbox for this new merged field, picklist is a few 100s of values.
@eygirard @AnnickMorin

**Comment by ghuotvez** [comment]
@AnnickMorin As-tu une nouvelle liste de valeur pour ce billet finalement?

**Comment by AnnickMorin** [comment]
En attente du retour de Pierre/Louise Corriveau. Je te reviens la dessus au courant de la semaine prochaine.

**Comment by ghuotvez** [comment]
Both field will be merge as well as picklist. Will need to rebuild UI accordingly and probably add searchability.

**Comment by ghuotvez** [comment]
Searchability has been dropped, since the picklist are dependant on input lithology, it gets filtered properly and it less long then one huge and long one.
